checando = input ('Digite algo: ')
print(checando.isnumeric())
print(checando.isalpha()) 
print(checando.isalnum())
print(checando.isupper())
print(checando.islower())
print(checando.istitle())
print(checando.isspace())
print(checando.isprintable())